import fs from "fs";
import path from "path";
import { exec } from "child_process";

/**
 * Resolves the Nginx configuration directory based on priority:
 * 1. Linux paths (/etc/nginx/sites-enabled, /etc/nginx/conf.d, /etc/nginx)
 * 2. NGINX_CONFIG_DIR from environment if it exists
 * 3. Returns null if none exist (do nothing)
 */
export function resolveNginxConfigDir(): string | null {
  const linuxPaths = [
    "/etc/nginx/sites-enabled",
    "/etc/nginx/conf.d",
    "/etc/nginx"
  ];

  for (const p of linuxPaths) {
    if (fs.existsSync(p)) {
      try {
        const stat = fs.statSync(p);
        if (stat.isDirectory()) {
          return p;
        }
      } catch {
        // ignore errors reading directory info
      }
    }
  }

  const envPath = process.env.NGINX_CONFIG_DIR;
  if (envPath) {
    if (fs.existsSync(envPath)) {
      try {
        const stat = fs.statSync(envPath);
        if (stat.isDirectory()) {
          return envPath;
        }
      } catch {
        // ignore
      }
    }
  }

  return null;
}

/**
 * Generates standard Nginx reverse proxy configuration to be able to use a domain name for a application running on a specific port.
 */
export function generateNginxConfig(domain: string, port: number): string {
  return `# Generated by Process Manager
server {
    listen 80;
    server_name ${domain};

    location /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;
}

/**
 * Writes Nginx configuration file for a domain
 */
export async function writeDomainConfig(domain: string, port: number): Promise<{ success: boolean; filePath?: string; warning?: string; error?: string }> {
  try {
    const configDir = resolveNginxConfigDir();
    if (!configDir) {
      return {
        success: true,
        warning: "Nginx-Konfigurationsordner nicht gefunden (weder unter Linux-Standardpfaden noch in NGINX_CONFIG_DIR). Es wurde keine Konfigurationsdatei geschrieben."
      };
    }

    const filePath = path.join(configDir, `${domain}.conf`);
    const content = generateNginxConfig(domain, port);

    fs.writeFileSync(filePath, content, "utf-8");
    return { success: true, filePath };
  } catch (error) {
    console.error(`Failed to write Nginx config for ${domain}:`, error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * Deletes Nginx configuration file for a domain
 */
export async function deleteDomainConfig(domain: string): Promise<{ success: boolean; warning?: string; error?: string }> {
  try {
    const configDir = resolveNginxConfigDir();
    if (!configDir) {
      return {
        success: true,
        warning: "Nginx-Konfigurationsordner nicht gefunden, es gibt keine Datei zu löschen."
      };
    }

    const filePath = path.join(configDir, `${domain}.conf`);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
    return { success: true };
  } catch (error) {
    console.error(`Failed to delete Nginx config for ${domain}:`, error);
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * Reloads Nginx configuration
 */
export function reloadNginx(): Promise<{ success: boolean; error?: string }> {
  return new Promise((resolve) => {
    const configDir = resolveNginxConfigDir();
    if (!configDir) {
      // If config dir doesn't exist, we do nothing and don't reload
      return resolve({ success: true });
    }

    const reloadCmd = process.env.NGINX_RELOAD_COMMAND || "nginx -s reload";
    exec(reloadCmd, (error, stdout, stderr) => {
      if (error) {
        console.error(`Nginx reload command failed: ${reloadCmd}`, error);
        resolve({
          success: false,
          error: stderr.trim() || error.message || "Befehl schlug fehl"
        });
      } else {
        resolve({ success: true });
      }
    });
  });
}

/**
 * Runs Certbot to obtain SSL certificate for a domain
 */
export function runCertbot(domain: string, email?: string): Promise<{ success: boolean; error?: string }> {
  return new Promise((resolve) => {
    const mail = email || process.env.AUTH_EMAIL || "";
    const emailFlag = mail ? `-m ${mail}` : "--register-unsafely-without-email";
    const cmd = `certbot --nginx -d ${domain} --non-interactive --agree-tos ${emailFlag}`;

    exec(cmd, (error, stdout, stderr) => {
      if (error) {
        console.error(`Certbot command failed for ${domain}:`, error);
        resolve({
          success: false,
          error: stderr.trim() || error.message || "Certbot schlug fehl"
        });
      } else {
        resolve({ success: true });
      }
    });
  });
}
